# Generated by Django 3.0.7 on 2024-05-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('nom_category', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('quantite', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorystock', to='stock.Category')),
            ],
        ),
    ]
