# Generated by Django 3.0.7 on 2024-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
