# Generated by Django 3.0.7 on 2024-04-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='quantite',
        ),
    ]
