# Generated by Django 3.0.7 on 2024-04-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20240422_1751'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prixunitaire', models.IntegerField(default=1)),
                ('montant', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prixunitaire', models.IntegerField(default=1)),
                ('montant', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsFactureAchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway', models.CharField(blank=True, max_length=50, null=True)),
                ('veh', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('po', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, max_length=50, null=True)),
                ('cess', models.CharField(blank=True, max_length=50, null=True)),
                ('tcs', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsFactureVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway', models.CharField(blank=True, max_length=50, null=True)),
                ('veh', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('po', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, max_length=50, null=True)),
                ('cess', models.CharField(blank=True, max_length=50, null=True)),
                ('tcs', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactureAchat',
            fields=[
                ('nofacture', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactureVente',
            fields=[
                ('nofacture', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=12)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gstin', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='stock',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='address',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Fournisseur',
        ),
        migrations.DeleteModel(
            name='PurchaseBill',
        ),
        migrations.DeleteModel(
            name='PurchaseBillDetails',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='SaleBill',
        ),
        migrations.DeleteModel(
            name='SaleBillDetails',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
        migrations.AddField(
            model_name='factureachat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achatfournisseur', to='transactions.Fournisseur'),
        ),
        migrations.AddField(
            model_name='detailsfacturevente',
            name='nofacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailsfactureventeno', to='transactions.FactureVente'),
        ),
        migrations.AddField(
            model_name='detailsfactureachat',
            name='nofacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodetailsfactureachat', to='transactions.FactureAchat'),
        ),
        migrations.AddField(
            model_name='articlevente',
            name='nofacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factureventeno', to='transactions.FactureVente'),
        ),
        migrations.AddField(
            model_name='articlevente',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlevente', to='stock.Stock'),
        ),
        migrations.AddField(
            model_name='articleachat',
            name='nofacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nofactureachat', to='transactions.FactureAchat'),
        ),
        migrations.AddField(
            model_name='articleachat',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleachat', to='stock.Stock'),
        ),
    ]
